version: "3.7"
services:
  auth:
    build: .
    restart: always
    ports:
      - "50051:50051"
    environment:
      - SECRET=super_serial_secret_10000
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.expose: "true"